FROM kestra/kestra:latest
# Utilise l’image officielle Kestra comme base pour ajouter des dépendances

USER root
# Passe en utilisateur root pour pouvoir installer des paquets système

RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    pip3 install --no-cache-dir pandas numpy requests openrouteservice python-dateutil sqlalchemy psycopg2-binary Faker openpyxl great-expectations pytest kafka-python
# Installe les librairies Python nécessaires au traitement, API, DB, tests et Kafka