FROM kestra/kestra:latest

USER root

RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    pip3 install --no-cache-dir pandas numpy requests openrouteservice python-dateutil sqlalchemy psycopg2-binary Faker openpyxl great-expectations pytest kafka-python