volumes:
  postgres-data-projet12: # Volume persistant pour stocker les données PostgreSQL
    driver: local # Utilise le driver local Docker pour la persistance
  kestra-data-projet12: # Volume persistant pour stocker les données Kestra
    driver: local
  redpanda-data: # Volume persistant pour stocker les données Redpanda
    driver: local
services:
  postgres: # Service de base de données PostgreSQL
    image: postgres:18 # Image Docker de PostgreSQL version 18
    volumes:
      - postgres-data-projet12:/var/lib/postgresql # Montage du volume persistant pour stocker les données PostgreSQL
    ports:
      # - "5432:5432" # Port exposé sur la machine locale
      - "5433:5432" # Port exposé sur la machine locale (5433 pour éviter les conflits avec d'autres services)
    environment:
      POSTGRES_DB: kestra # Nom de la base de données PostgreSQL
      POSTGRES_USER: kestra # Nom d'utilisateur PostgreSQL
      POSTGRES_PASSWORD: k3str4 # Mot de passe PostgreSQL
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"] # Vérifie si la base de données est prête
      interval: 30s # Intervalle de vérification
      timeout: 10s # Temps maximum de vérification avant echec
      retries: 10 # Nombre de tentatives de vérification avant de considérer le service comme down

  kestra: # Service d'orchestration Kestra
    build:
      context: . # Contexte de build (dossier courant)
      dockerfile: Dockerfile.kestra # Fichier Dockerfile utilisé pour le build
    image: kestra_custom_projet12:latest # Image Docker de Kestra
    container_name: kestra_projet12 # Nom du conteneur
    pull_policy: always # Force Docker à vérifier les mises à jour de l’image
    # Kestra, by default, has a termination grace period of 5m. We need to wait a little more to be sure no active tasks are running.
    stop_grace_period: 6m # Délai avant arrêt forcé pour laisser finir les tâches
    # Note that this setup with a root user is intended for development purpose.
    # Our base image runs without root, but the Docker Compose implementation needs root to access the Docker socket
    user: "root" # Exécute le conteneur en root (nécessaire pour accès Docker socket)
    command: server standalone # Lance le serveur Kestra en mode standalone
    volumes:
      - kestra-data-projet12:/app/storage # Montage du volume persistant pour stocker les données Kestra
      - /var/run/docker.sock:/var/run/docker.sock # Montage du socket Docker pour accès aux conteneurs Docker
      - /tmp/kestra-wd:/tmp/kestra-wd # Montage du volume persistant pour stocker les données temporaires de Kestra
      - C:/Users/zakar_2tvurct/Desktop/Formation_Data_Engineer/Projet_12/Projet_12/sport_data_solution:/data/sport_data_solution # Montage du volume persistant pour stocker les données de sport_data_solution
    env_file:
        - ../.env # Fichier .env contenant les variables d'environnement
    environment:
      KESTRA_CONFIGURATION: | # Configuration interne de Kestra en YAML inline
        datasources:
          postgres:
            url: jdbc:postgresql://postgres:5432/kestra # URL de connexion à la base de données PostgreSQL
            driverClassName: org.postgresql.Driver
            username: kestra 
            password: k3str4
        kestra:
          # server:
          #   basic-auth:
          #     username: admin@kestra.io # it must be a valid email address
          #     password: Admin1234! # it must be at least 8 characters long with uppercase letter and a number
          repository:
            type: postgres
          storage:
            type: local
            local:
              base-path: "/app/storage"
          queue:
            type: postgres
          tasks:
            tmp-dir:
              path: /tmp/kestra-wd/tmp
          url: http://localhost:8080/
    ports:
      - "8080:8080" # Port UI Kestra
      - "8081:8081"  # Port API/Services internes
    depends_on:
      postgres:
        condition: service_started # Attend que PostgreSQL soit démarré avant de démarrer Kestra

  # 🔴 REDPANDA

  redpanda-0: # Service de broker Kafka Redpanda (équivalent Kafka)
    image: docker.redpanda.com/redpandadata/redpanda:v25.3.4 # Image Docker de Redpanda version 25.3.4
    container_name: redpanda-0 # Nom du conteneur
    command:
      - redpanda
      - start # Lance le broker Kafka
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://redpanda-0:9092,external://localhost:19092
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
      - --advertise-pandaproxy-addr internal://redpanda-0:8082,external://localhost:18082
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:18081
      - --rpc-addr redpanda-0:33145
      - --advertise-rpc-addr redpanda-0:33145
      - --mode dev-container
      - --smp 1
    volumes:
      - redpanda-data:/var/lib/redpanda/data # Persistance des données du broker
    ports:
      - "19092:19092" # Port Kafka externe
      - "18081:18081" # Port schema registry
      - "18082:18082" # Port pandaproxy
      - "19644:9644" # Port Port admin Redpanda

  redpanda-console: # Service de console Redpanda. Interface web pour gérer Redpanda
    image: docker.redpanda.com/redpandadata/console:v3.5.0 # Image Docker de Redpanda console version 3.5.0
    container_name: redpanda-console # Nom du conteneur
    depends_on:
      - redpanda-0 # Attend que le broker Kafka soit démarré avant de démarrer la console
    entrypoint: /bin/sh
    command: -c 'echo "$$CONSOLE_CONFIG_FILE" > /tmp/config.yml; /app/console' # Lance la console Redpanda
    environment:
      CONFIG_FILEPATH: /tmp/config.yml # Chemin du fichier de configuration
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda-0:9092"]
    ports:
      - "8082:8080" # Port console Redpanda

  redpanda-init: # Service de création du topic Kafka
    image: docker.redpanda.com/redpandadata/redpanda:v25.3.4 # Image Docker de Redpanda version 25.3.4
    depends_on:
      - redpanda-0 # Attend que le broker Kafka soit démarré avant de démarrer le init
    entrypoint: >
      bash -c "
      sleep 15 &&
      rpk topic create sport_activity --brokers redpanda-0:9092 || true
      "
  producer: # Service de production des activités sportives
    build: ../producer # Contexte de build (dossier producer)
    container_name: producer # Nom du conteneur
    depends_on:
      - redpanda-0 # Attend que le broker Kafka soit démarré avant de démarrer le producer
      - postgres # Attend que PostgreSQL soit démarré avant de démarrer le producer
    env_file:
      - ../.env # Fichier .env contenant les variables d'environnement
    volumes:
      - ../sport_data_solution:/data/sport_data_solution # Montage du volume persistant pour stocker les données de sport_data_solution
      - ../producer:/app # Montage du volume persistant pour stocker le code du producer
    networks:
      - default # Réseau par défaut